const listadoAlumnos = [
    'Adamo Fernando',
    'Aguirre Diego',
    'Almaraz Juan Carlos',
    'Aritto	Daniela',
    'Barral	Martín',
    'Bianchi Sergio',
    'Blanco	Ezequiel',
    'Castiglione Marco',
    'Dominguez Juan Martín',
    'Eula Ayelén',
    'Fleitas Nestor David',
    'Galanternik Guido',
    'Giraldi Nicolás',
    'Gutierrez Ibañez José',
    'Heller	Camilo',
    'Imperatori	Bárbara',
    'Korn Oliver',
    'Moreno Seoane María Lucía',
    'Ramirez Ezequiel',
    'Rodriguez Diana',
    'Rojas Andrés',
    'Sánchez Eduardo',
    'Schenone Jorge',
    'Taboada Franco',
    'Tomaso	Eugenio',
    'Moreno Seoane María Lucía',
    'Matias Blayer',
    'Nicolas Quiroz'
]

const preguntas = [
    '¿En qué deporte creés que le podrías ganar a tu mentor/a?',
    '¿Cual es tu gusto de helado preferido? Fundamente su respuesta.',
    '¿Sabés andar en bicicleta? ¿Cómo aprendiste?',
    '¿Cuál fue la mejor película/serie que viste? (o libro que leiste)',
    '¿Qué es lo que mejor sabés cocinar?',
    'Si tuvieras que elegir un solo plato de comida para comer por el resto de tu vida, ¿cuál sería?',
    '¿Preferís el verano o el invierno? ¿Por qué?',
    '¿Si pudieras viajar a cualquier época (pasado o futuro), cuándo elegirías?',
    '¿Cuál es la mejor marca de alfajor? Fundamente.',
    'Si pudieras conocer a cualquier persona de la historia, ¿a quién elegirías?',
    'Si tuvieses que tirarte en una pileta repleta de algo, ¿de qué sería?',
    'Qué decías cuando eras chiquito y te preguntaban: ¿qué querés ser de grande?',
    '¿Cual es tu película favorita de starwars?'
]